
server:
  port: ${PORT:0}
spring:
 application:
  name: service-laptops
 mvc:
  pathmatch:
    matching-strategy: ANT_PATH_MATCHER
eureka:
 client:
  service-url:
   defaultZone: https://localhost:8761/eureka
 instance:
  instance-id: ${spring.aaplication.name}:${spring.application.instance_id:${random.value}}